{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f4db8b7f_4f7b3448",
        "filename": "requester/handler.hpp",
        "patchSetId": 5
      },
      "lineNbr": 166,
      "author": {
        "id": 1000938
      },
      "writtenOn": "2023-08-25T07:28:28Z",
      "side": 1,
      "message": "Can we have an error statement before assert?",
      "revId": "377dd587d62ab891e3f054eb339c6b0721ab327d",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}